"""create tasks table

Revision ID: 32c551dadb20
Revises: b43322b4d140
Create Date: 2025-02-28 03:04:58.452448

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "32c551dadb20"
down_revision: Union[str, None] = "b43322b4d140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
